name: Update FunPay reviews and TG posts
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug: show repo root and action folder
        run: |
          echo "PWD: $(pwd)"
          echo "Repo root listing:"
          ls -la
          echo ""
          echo ".github listing:"
          ls -la .github || true
          echo ""
          echo ".github/actions listing:"
          ls -la .github/actions || true
          echo ""
          echo ".github/actions/update-data listing:"
          ls -la .github/actions/update-data || true
        shell: bash

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies (cd then npm ci)
        run: |
          if [ -d ".github/actions/update-data" ]; then
            cd .github/actions/update-data
            echo "Running npm ci in: $(pwd)"
            npm ci
          else
            echo "Directory .github/actions/update-data not found; aborting with diagnostic listing"
            ls -la || true
            exit 1
          fi
        shell: bash

      - name: Run scraper (cd then node)
        env:
          FUNPAY_USER_URL: "https://funpay.com/users/11006828/"
          TG_CHANNEL_WEB: "https://t.me/s/sanzenand_fp"
        run: |
          cd .github/actions/update-data
          echo "Running scraper from: $(pwd)"
          node scrape.js
          # ensure generated files moved to repo root if script writes to cwd
          if [ -f reviews.json ]; then
            mv reviews.json "$GITHUB_WORKSPACE/" || true
          fi
          if [ -f tg_posts.json ]; then
            mv tg_posts.json "$GITHUB_WORKSPACE/" || true
          fi
        shell: bash

      - name: Show generated files (debug)
        run: |
          echo "Root listing after run:"
          ls -la "$GITHUB_WORKSPACE" || true
          echo "reviews.json preview:"
          head -n 60 reviews.json || true
          echo "tg_posts.json preview:"
          head -n 60 tg_posts.json || true
        shell: bash

      - name: Commit data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add reviews.json tg_posts.json || true
          git commit -m "Update reviews and tg posts" || echo "No changes to commit"
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
